### ISSUE TITLE
Ansible TASK [Gathering Facts] fails to connect galora_nodes through SSH

### ISSUE THREAD

**Issue by joonat** [CSC-IT-Center-for-Science/etherpad-deployment-demo#1]
Thank you for the interesting deployment-demo. This set of script has been created and tested some years ago, so it could be that something has changed since.

Unfortunately I have not enough knowledge to solve this myself yet I think if it's possible to update the demo (if needed) the others won't have to face the same thing. Or maybe this is at my end. Anyhow:

These are the parameters defined in my-heat-params.yml file
```

parameter_defaults:
  ssh_key_name: 'my-key'
  etherpad_node_flavor: 'standard.tiny'
  etherpad_node_image: 'CentOS-7'
  etherpad_node_allow_ssh_cidr: '0.0.0.0/0'
  etherpad_node_allow_http_cidr: '0.0.0.0/0'
  galera_node_flavor: 'standard.tiny'
  galera_node_image: 'CentOS-7'
  etherpad_network: 'project_1234567'
```

And the following error raises while galera playbook is played:

![sh_ssh_fail](https://user-images.githubusercontent.com/1643787/158057050-00bf66d4-08ac-4d93-bf42-90ccdff1e4b5.png)

My understanding is that the traffic should flow through ansible_ssh_host which do see those IP addresses and computers behind them. But for some reason it is not doing that or perhaps those machines are not available and that is the reason for error message. But based on other debug print from ansible playbook and when checked through the web interface, that should not be the case.

Thank you in advance.
